apiVersion: apps/v1
kind: Deployment
metadata:
  name: qa-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qa-bot
  template:
    metadata:
      labels:
        app: qa-bot
    spec:
      containers:
        - name: qa-bot
          image: quant-bot/qa-bot:latest
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
